/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskAgentRouteImport } from './routes/_desk/agent'
import { Route as DeskCasesRouteImport } from './routes/_desk/cases'
import { Route as DeskMatrixRouteImport } from './routes/_desk/matrix'
import { Route as DeskSignalsRouteImport } from './routes/_desk/signals'
import { Route as DeskStockRouteImport } from './routes/_desk/stock'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAgentRoute = DeskAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCasesRoute = DeskCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => DeskRoute,
} as any)
const DeskMatrixRoute = DeskMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSignalsRoute = DeskSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DeskRoute,
} as any)
const DeskStockRoute = DeskStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/agent': typeof DeskAgentRoute
  '/cases': typeof DeskCasesRoute
  '/matrix': typeof DeskMatrixRoute
  '/signals': typeof DeskSignalsRoute
  '/stock': typeof DeskStockRoute
}
export interface FileRoutesByTo {
  '/agent': typeof DeskAgentRoute
  '/cases': typeof DeskCasesRoute
  '/matrix': typeof DeskMatrixRoute
  '/signals': typeof DeskSignalsRoute
  '/stock': typeof DeskStockRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/_desk/agent': typeof DeskAgentRoute
  '/_desk/cases': typeof DeskCasesRoute
  '/_desk/matrix': typeof DeskMatrixRoute
  '/_desk/signals': typeof DeskSignalsRoute
  '/_desk/stock': typeof DeskStockRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent' | '/cases' | '/matrix' | '/signals' | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to: '/agent' | '/cases' | '/matrix' | '/signals' | '/stock' | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/_desk/agent'
    | '/_desk/cases'
    | '/_desk/matrix'
    | '/_desk/signals'
    | '/_desk/stock'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/agent': {
      id: '/_desk/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof DeskAgentRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/cases': {
      id: '/_desk/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof DeskCasesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/matrix': {
      id: '/_desk/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof DeskMatrixRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/signals': {
      id: '/_desk/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof DeskSignalsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/stock': {
      id: '/_desk/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof DeskStockRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskAgentRoute: typeof DeskAgentRoute
  DeskCasesRoute: typeof DeskCasesRoute
  DeskMatrixRoute: typeof DeskMatrixRoute
  DeskSignalsRoute: typeof DeskSignalsRoute
  DeskStockRoute: typeof DeskStockRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskAgentRoute: DeskAgentRoute,
  DeskCasesRoute: DeskCasesRoute,
  DeskMatrixRoute: DeskMatrixRoute,
  DeskSignalsRoute: DeskSignalsRoute,
  DeskStockRoute: DeskStockRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
